// src/lib/components/DarkmodeButton.svelte
<script lang="ts">
  import { darkmode } from "$lib/stores/darkmode";
  import SunIcon from '$lib/components/svg/SunIcon.svelte';
  import MoonIcon from '$lib/components/svg/MoonIcon.svelte';
  import { slide }from "svelte/transition";

  let inTransition = {
    duration: 400, delay: 500
  };

  let outTransition = {
    duration: 400
  }

  function toggleDarkmode() {
    if ($darkmode) {
      $darkmode = false;
      document.documentElement.classList.remove("dark");
      localStorage.setItem("theme", "light");
    } else {
      $darkmode = true;
      document.documentElement.classList.add("dark");
      localStorage.setItem("theme", "dark");
    }
  }
  
</script>

<button 
  class="p-2 text-purple-8000 dark:text-yellow-200"
  on:click={toggleDarkmode}
>
  {#if $darkmode}
    <div
      in:slide={inTransition}
      out:slide={outTransition}
    >
    <SunIcon class="w-8 h-8 fill-current" />
    </div>
  {:else}
    <div>
      <MoonIcon class="w-8 h-8 fill-current" />
    </div>
  {/if}
</button>

// components/layout/DarkmodeButton.tsx
'use client';

import { useTheme } from '@/lib/contexts/theme-context';
import { MoonIcon, SunIcon } from '@/components/icons';
import { motion, AnimatePresence } from 'framer-motion';

export function DarkmodeButton() {
  const { theme, toggleTheme } = useTheme();
  const isDark = theme === 'dark';

  const slideVariants = {
    enter: {
      x: -20,
      opacity: 0,
    },
    center: {
      x: 0,
      opacity: 1,
    },
    exit: {
      x: 20,
      opacity: 0,
    },
  };

  return (
    <button
      onClick={toggleTheme}
      className="p-2 text-purple-800 dark:text-yellow-200"
      aria-label={isDark ? 'Switch to light mode' : 'Switch to dark mode'}
    >
      <AnimatePresence mode="wait">
        {isDark ? (
          <motion.div
            key="sun"
            variants={slideVariants}
            initial="enter"
            animate="center"
            exit="exit"
            transition={{ duration: 0.2 }}
          >
            <SunIcon className="w-8 h-8 fill-current" />
          </motion.div>
        ) : (
          <motion.div
            key="moon"
            variants={slideVariants}
            initial="enter"
            animate="center"
            exit="exit"
            transition={{ duration: 0.2 }}
          >
            <MoonIcon className="w-8 h-8 fill-current" />
          </motion.div>
        )}
      </AnimatePresence>
    </button>
  );
}
